platform :ios, '11.0'
use_frameworks!

target 'ET' do
  inhibit_all_warnings!

  pod 'RxSwift', '4.5.0'
  pod 'RxCocoa', '4.5.0'
  pod 'Moya/RxSwift', '12.0.1'
  pod 'Moya-ObjectMapper/RxSwift', '2.8'
  pod 'ObjectMapper', '3.4.2'
  pod 'DeviceKit', '2.0.0'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'


end
